### ISSUE TITLE
invalid literal for int() with base 10:"

### ISSUE THREAD

**Issue by Misioslav** [xtero/CrunchyREroll#13]
Hi! So, after a couple of days of not using Kodi, I found some time to watch some anime today, and when I turned Kodi on I noticed an error 401 on the beta-api URL. I've tried resetting the login data etc but no joy. So I've decided to uninstall the plugin (together with settings, etc.) and install it again (1.0.2 version).
I've filled out all the data, etc., and when I want to enter "Watchlist" or any other menu element I'm getting the error `invalid literal for int() with base 10:"` and I can't watch anything. I've double and triple-checked login data, etc.

I've checked via the mobile app and crunchy works fine for me also via the Android TV app.

Update: I've just noticed that there is a 1.0.3 version. So I've installed it but still the same error then I've reinstalled it and still the same error.
Update 2: I've checked version 1.0.1 it just throws auth error (which is understandable) but not the other error.

**Comment by xbezdick** [comment]
.kodi/addons/plugin.video.crunchyreroll/resources/settings.xml

        <setting id="resolution" type="number" default="1080"/>


someone fortgot to add resolution settings or pull it from kodi?

**Comment by xbezdick** [comment]
``2024-04-15 20:34:30.512 T:9652    error <general>: [Crunchyroll.support] invalid literal for int() with base 10: ''
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                                       ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.crunchyreroll/resources/lib/main.py", line 80, in popular
                                                       cr = utils.init_crunchyroll_client()
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.crunchyreroll/resources/lib/utils.py", line 185, in init_crunchyroll_client
                                                       "resolution": int(addon.getSetting("resolution"))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   ValueError: invalid literal for int() with base 10: ''

**Comment by xtero** [comment]
Sorry, I'm in holidays. I'll check when I come back.
I'll probably remove this setting as it's not used and is handled by the inpustream.adaptive plugin

**Comment by xtero** [comment]
fixed in version v1.0.4
