### ISSUE TITLE
infolabel 'episode', is not of type '<class 'int'>'

### ISSUE THREAD

**Issue by 0xMar** [xtero/CrunchyREroll#9]
Hi. Upon attempting to access an anime folder, I encountered the following error: "**value of '7.5' for infolabel 'episode', is not of type '<class 'int'>**". This issue arises as an instance in the anime series 'Solo Leveling' and 'Kuroko no Basuke'.

Kodi log:

```
2024-03-23 20:39:07.677 T:730348   error <general>: [Crunchyroll.support] value of '7.5' for infolabel 'episode', is not of type '<class 'int'>'
                                                   Traceback (most recent call last):
                                                     File "/home/victor/.kodi/addons/script.module.codequick/lib/codequick/listing.py", line 258, in __setitem__
                                                       value = type_converter(value)
                                                               ^^^^^^^^^^^^^^^^^^^^^
                                                   ValueError: invalid literal for int() with base 10: '7.5'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/victor/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/victor/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/victor/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/victor/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                                       ^^^^^^^^^^^^^^^^^^^
                                                     File "/home/victor/.kodi/addons/plugin.video.crunchyreroll/resources/lib/main.py", line 121, in show_season
                                                       item = Listitem.from_dict(play_episode, **infos)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/victor/.kodi/addons/script.module.codequick/lib/codequick/listing.py", line 762, in from_dict
                                                       item.info.update(info)
                                                     File "<frozen _collections_abc>", line 949, in update
                                                     File "/home/victor/.kodi/addons/script.module.codequick/lib/codequick/listing.py", line 261, in __setitem__
                                                       raise TypeError(msg % (value, key, type_converter))
                                                   TypeError: value of '7.5' for infolabel 'episode', is not of type '<class 'int'>'

```

Version: latest from develop branch.

**Comment by Misioslav** [comment]
Same happens for me. It happens on both the main and develop branches. I cant enter anime directory but if its just episode it will play it.

**Comment by psycorama** [comment]
I did some snooping and found a workaround (for now)
```patch
--- listing.py_backup   2024-04-05 21:36:25.606667422 +0200
+++ listing.py  2024-04-05 21:36:31.142602327 +0200
@@ -255,7 +255,7 @@
             # Convert value to required type needed for this infolabel
             if type_converter:
                 try:
-                    value = type_converter(value)
+                    value = type_converter(str(value).replace('.', ''))
                 except ValueError:
                     msg = "value of '%s' for infolabel '%s', is not of type '%s'"
                     raise TypeError(msg % (value, key, type_converter))
```

this removes the '.' from the filename and even let you play the episode (at least for Solo Leveling)

**Comment by xtero** [comment]
The version 1.0.2 should fix the issue
